---
nginx:    
  build: ./nginx/  
  container_name: nginx-container-dev  
  ports:  
   - 8008:80  
  links:  
   - php  
  volumes_from:  
   - app-data  

php:    
  build: ./php/  
  container_name: php-container-dev  
  expose:  
   - 9000  
  links:  
   - mysql  
  volumes_from:  
   - app-data  

app-data:    
  image: php:7.0-fpm  
  container_name: app-data-container-dev  
  volumes:  
   - ./www/html/:/var/www/html/  
  command: "true"
      
mysql:    
  image: mysql:5.7  
  container_name: mysql-container-dev 
  ports:
   - 3307:3306 
  volumes_from:  
   - mysql-data  
  environment:  
   MYSQL_ROOT_PASSWORD: secret  
   MYSQL_DATABASE: mydb  
   MYSQL_USER: myuser  
   MYSQL_PASSWORD: password  

mysql-data:    
  image: mysql:5.7  
  container_name: mysql-data-container-dev  
  volumes:  
   - /var/lib/mysql  
  command: "true" 


